import re

raw_data = """**Jurisdicción**;Derecho Procesal;Orgánico;Poder-deber que tienen los tribunales para conocer y resolver, por medio del proceso y con efecto de cosa juzgada, los conflictos de intereses de relevancia jurídica.;La Corte Suprema resolviendo un recurso extraordinario de revisión o casación en el fondo con autoridad soberana plena,.;Colombo Campbell;Es indelegable e improrrogable.|Su falta genera la inexistencia procesal del acto.

**Competencia**;Derecho Procesal;Orgánico;Esfera, grado o medida fijada por el legislador para que la jurisdicción se ejerza por cada tribunal específico.;Un juez de letras conociendo de un asunto civil de mayor cuantía en su territorio jurisdiccional.;Art. 108 COT;Puede delegarse parcialmente mediante exhortos.|Su infracción o falta genera la nulidad procesal.

**Prórroga de la Competencia**;Derecho Procesal;Orgánico;Acuerdo expreso o tácito de las partes para otorgar competencia a un tribunal que naturalmente no es el competente para conocer del asunto.;El demandado contesta una demanda civil ante un tribunal de distinto territorio sin alegar la incompetencia.;Art. 187 CPC;Procede solo en asuntos civiles contenciosos de primera instancia.|Permite alterar únicamente el factor territorio, nunca la materia o fuero.

**Regla de Radicación**;Derecho Procesal;Orgánico;Principio normativo que establece que, radicado con arreglo a la ley el conocimiento de un negocio ante tribunal competente, no se alterará esta competencia por causa sobreviniente.;Un demandado cambia de domicilio a otra ciudad durante el juicio, pero el tribunal original sigue siendo el competente para fallar,.;Art. 109 COT;Requiere la intervención formal de un tribunal competente mediante notificación válida.|Genera el estado de litis pendencia y fija irremediablemente la competencia.

**Equivalentes Jurisdiccionales**;Derecho Procesal;Teoría General;Formas de solución de conflictos distintas del proceso jurisdiccional que producen un efecto vinculante asimilable a la cosa juzgada,.;La celebración de un contrato de transacción o un avenimiento aprobado por el juez,.;Doctrina Procesal (Carnelutti);Constituyen actos de autocomposición que ponen término anticipado al litigio.|Producen eficacia de cosa juzgada material al igual que una sentencia definitiva.

**Proceso**;Derecho Procesal;Teoría General;Medio idóneo para dirimir imparcialmente, por acto de juicio de autoridad, un conflicto de relevancia jurídica mediante una resolución que eventualmente puede adquirir la fuerza de la cosa juzgada,.;La totalidad de la secuela de actos desde la demanda hasta el cumplimiento de la sentencia para el cobro de una deuda.;Doctrina Procesal;Es un concepto abstracto y único enfocado en la finalidad de resolver la controversia.|Su culminación lógica y esperada es la dictación de una sentencia firme.

**Procedimiento**;Derecho Procesal;Teoría General;Conjunto de formalidades, trámites, ritos externos o actuaciones a través de las cuales se desarrolla materialmente el proceso judicial,.;El juicio ordinario que establece etapas estrictas de discusión, prueba y fallo.;Doctrina Procesal;Constituye el aspecto exterior, formal y dinámico del fenómeno procesal.|Existen múltiples procedimientos (ordinario, sumario, ejecutivo) para sustanciar procesos de diversa naturaleza.

**Juicio**;Derecho Procesal;Teoría General;Controversia jurídica y actual producida entre dos o más personas sobre un derecho y que se somete a la decisión jurisdiccional de un tribunal,.;El litigio puntual entre arrendador y arrendatario por el no pago de las rentas,.;Casarino Viterbo;Sus elementos constitutivos son la contienda, las partes y el tribunal llamado a resolverla.|Suele utilizarse doctrinariamente como el procedimiento específico a través del cual se desarrolla el proceso.

**Partes**;Derecho Procesal;Sujetos Procesales;Aquellas personas que sostienen formalmente ante un tribunal una contienda jurídica y actual acerca de sus propios derechos e intereses.;El acreedor demandante que exige el pago y el deudor demandado que rechaza la deuda.;Doctrina Procesal;Se clasifican fundamentalmente en directas o principales e indirectas o terceros.|Para intervenir válidamente requieren contar con capacidad procesal.

**Terceros**;Derecho Procesal;Sujetos Procesales;Personas distintas del demandante y del demandado que comparecen al juicio por tener comprometido en él un derecho, sosteniendo peticiones.;Un legatario que decide intervenir voluntariamente en el juicio donde los herederos discuten la nulidad del testamento.;Doctrina Procesal;Su intervención procedimental se denomina jurídicamente como tercería.|Se subclasifican en terceros coadyuvantes, independientes y excluyentes.

**Patrocinio**;Derecho Procesal;Comparecencia en Juicio;Contrato por el cual las partes o interesados en un asunto judicial encomiendan a un abogado habilitado la defensa técnica de sus pretensiones ante los tribunales.;Un abogado que asume la dirección jurídica de un caso asumiendo la firma y responsabilidad en el primer escrito.;Ley Nº 18.120;El profesional asume la responsabilidad civil, criminal y disciplinaria de la defensa.|Se diferencia del mandato judicial en que este último se restringe a la mera representación procesal.

**Mandato Judicial**;Derecho Procesal;Comparecencia en Juicio;Contrato procesal mediante el cual una persona otorga a otra facultades suficientes para que la represente formal y válidamente ante los tribunales de justicia.;Una persona confiere mandato mediante escritura pública a un procurador del número para tramitar su caso civil,.;Ley Nº 18.120;Debe recaer obligatoriamente en abogados habilitados, procuradores del número o postulantes de la corporación.|Su no constitución legal acarrea que el tribunal tenga por no presentado el escrito respectivo.

**Demanda**;Derecho Procesal;Juicio Ordinario;Acto procesal introductivo de instancia por virtud de la cual el actor somete su pretensión al juez, con las formas requeridas por la ley, pidiendo una sentencia favorable en su interés.;El escrito principal mediante el cual el actor exige indemnización por incumplimiento de un contrato.;Art. 254 CPC / Couture;Es la vía formal y material a través de la cual se ejercita la acción procesal.|Fija los límites del juicio y el marco sobre el cual deberá recaer la congruencia de la sentencia definitiva.

**Emplazamiento**;Derecho Procesal;Disposiciones Comunes;Notificación de la demanda, a la cual se agrega la orden de que el notificado comparezca al tribunal dentro del término señalado por éste.;El receptor notifica la demanda civil al deudor, abriendo el plazo fatal legal para que este conteste.;Doctrina Procesal;Se compone de dos elementos copulativos: la notificación legal y el transcurso íntegro del plazo.|Su omisión o defecto grave configura un vicio esencial que anula la validez de todo el procedimiento.

**Notificación Personal**;Derecho Procesal;Notificaciones;Forma legal de notificación que consiste en entregar directamente a la persona a quien se debe notificar, en forma física, copia íntegra de la resolución y de la solicitud respectiva.;El receptor judicial entrega en propias manos del demandado la resolución que admite a tramitación la primera demanda civil,.;Art. 40 CPC;Es la regla obligatoria e ineludible para la primera notificación a las partes en toda gestión judicial,.|Garantiza de forma directo el efectivo conocimiento del acto procesal fundamental.

**Notificación por el Estado Diario**;Derecho Procesal;Notificaciones;Ficción legal en que se entiende válidamente notificada una resolución por el solo hecho de incluirse la noticia de su dictación en una nómina electrónica diaria,.;La resolución de mero trámite de traslado se incorpora en el sistema informático del tribunal quedando las partes legalmente informadas.;Art. 50 CPC;Constituye la regla generalísima para notificar actos de tramitación normal en el proceso civil.|La inclusión se realiza en un estado electrónico disponible permanentemente en el portal del Poder Judicial.

**Plazo Fatal**;Derecho Procesal;Plazos Procesales;Espacio de tiempo en que la posibilidad de ejercer un derecho o ejecutar un acto procesal se extingue automáticamente a su vencimiento por el solo ministerio de la ley.;El plazo legal de quince días para contestar la demanda ordinaria que precluye automáticamente si no se presenta el escrito a tiempo.;Art. 64 CPC;La gran mayoría de los plazos que establece el Código de Procedimiento Civil revisten esta naturaleza perentoria.|No requieren de declaración judicial ni certificado de rebeldía previo para que opere su pleno efecto preclusivo.

**Rebeldía**;Derecho Procesal;Plazos Procesales;Situación jurídica que se le produce al litigante que deja de evacuar un trámite o de practicar una diligencia en el plazo que señala el tribunal.;El demandante no evacúa el trámite de observaciones a la prueba, por lo que el tribunal declara evacuado el trámite en su rebeldía.;Art. 78 CPC;Obliga al tribunal, de oficio o a petición de parte, a declarar el trámite por evacuado y dar curso progresivo a la sustanciación.|Puede ser objeto de rescisión si la parte demuestra fehacientemente haber estado impedida por fuerza mayor.

**Excepciones Dilatorias**;Derecho Procesal;Juicio Ordinario;Defensas procesales que tienen por objeto corregir los vicios de validez procesal al momento de formarse la relación jurídica y corregir el procedimiento.;El demandado alega la incompetencia del tribunal o la ineptitud del libelo por falta de claridad en las peticiones de la demanda.;Art. 303 CPC;Se tramitan obligatoriamente como un incidente de previo y especial pronunciamiento.|Buscan sanear y purificar la relación jurídica procesal antes de entrar al debate del fondo.

**Excepciones Perentorias**;Derecho Procesal;Juicio Ordinario;Defensas jurídicas de carácter sustancial que miran directamente al fondo del asunto y tienen por exclusivo objeto enervar, destruir o extinguir la acción deducida.;Frente a la demanda de cobro de dinero, el demandado contesta oponiendo el pago efectivo de la deuda o la prescripción.;Doctrina Procesal;A diferencia de las dilatorias, no suspenden el proceso, sino que persiguen el rechazo íntegro de la demanda en la sentencia final.|Suelen coincidir e identificarse directamente con los modos normativos civiles de extinguir las obligaciones.

**Reconvención**;Derecho Procesal;Juicio Ordinario;Demanda procesal nueva que el demandado deduce en contra del demandante original en el propio escrito de contestación de la demanda.;En un juicio ordinario por incumplimiento contractual, el demandado contesta y a su vez demanda exigiendo indemnización por mejoras,.;Art. 314 CPC;Se tramita conjuntamente y se falla de forma obligatoria en la misma sentencia definitiva de la acción principal.|Materializa el principio de economía procesal y evita el alto riesgo de dictar sentencias contradictorias.

**Incidentes**;Derecho Procesal;Disposiciones Comunes;Toda cuestión procedimental accesoria a un juicio principal que requiere de un pronunciamiento judicial especial, con o sin audiencia de partes,.;Un litigante promueve la nulidad de una notificación defectuosa o solicita el alzamiento judicial de una medida precautoria.;Art. 82 CPC;Se pueden subclasificar procesalmente en incidentes ordinarios, especiales, de previo y especial pronunciamiento, conexos o inconexos,.|Su tramitación comprende una etapa de discusión, prueba y un fallo emitido típicamente en un auto o interlocutoria,.

**Acumulación de Autos**;Derecho Procesal;Incidentes Especiales;Incidente procesal especial que tiene por objeto obtener que el tribunal ordene agrupar materialmente dos o más procesos pendientes y conexos para tramitarlos y fallarlos conjuntamente.;Se acumula un juicio declarativo de nulidad de contrato a otro que persigue el cobro coactivo del mismo.;Art. 92 CPC;Su finalidad suprema y fundante es mantener la continencia de la causa y evitar el pronunciamiento de sentencias contradictorias.|Exige copulativamente que los juicios afectados se encuentren en instancias análogas y sometidos al mismo procedimiento legal.

**Abandono del Procedimiento**;Derecho Procesal;Incidentes Especiales;Sanción procesal que declara el término anticipado del procedimiento por la inactividad de las partes que han cesado en su prosecución durante seis meses.;El juicio civil se estanca ocho meses sin que nadie pida prueba, por lo que el demandado solicita al juez que declare extinguido el proceso.;Art. 152 CPC;Provoca la pérdida de todo lo obrado en el juicio, castigando la negligencia de los litigantes.|No extingue directamente la pretensión ni la acción material subyacente, permitiendo al actor entablar una demanda nueva.

**Desistimiento de la Demanda**;Derecho Procesal;Incidentes Especiales;Acto jurídico procesal unilateral, formalizado por el actor, mediante el cual manifiesta su voluntad de renunciar a la pretensión hecha valer, extinguiendo el proceso,.;El demandante, percatándose de un error estratégico insalvable, presenta un escrito desistiéndose tras haber notificado al demandado.;Art. 148 CPC;Se tramita rigurosamente como un incidente y requiere una resolución jurisdiccional interlocutoria que lo acoja.|Produce un efecto definitivo extinguiendo la pretensión procesal originando la fuerza de cosa juzgada.

**Medidas Prejudiciales**;Derecho Procesal;Medidas Cautelares;Providencias de naturaleza preparatoria o conservadora que puede o debe decretar el tribunal, antes del inicio formal de un juicio, para hacer posible o facilitar las futuras acciones o defensas.;Un futuro demandante solicita la exhibición judicial de los libros de contabilidad de la empresa adversaria para fundar precisamente su demanda,.;Art. 273 CPC;La doctrina procesal las subclasifica en preparatorias, probatorias y netamente precautorias prejudiciales.|Buscan garantizar razonablemente que la entrada al futuro litigio sea con los elementos de juicio y pruebas indispensables.

**Medidas Precautorias**;Derecho Procesal;Medidas Cautelares;Providencias dictadas por el juez durante el curso del juicio que están dirigidas a asegurar el resultado práctico y el cumplimiento patrimonial de la acción deducida,.;La retención de dineros bancarios del demandado o la prohibición judicial de celebrar actos sobre un inmueble disputado.;Art. 290 CPC;Exigen comprobar al menos la presunción grave del derecho que se reclama y requieren caución en ciertos casos.|Son resoluciones esencialmente provisionales, limitadas a los bienes necesarios y pueden ser sustituidas por garantías suficientes.

**Resoluciones Judiciales**;Derecho Procesal;Teoría de las Resoluciones;Acto jurídico procesal que emana formalmente del tribunal o sus auxiliares, destinado a dar curso progresivo al procedimiento (sustanciar) o a fallar la controversia del juicio.;Desde un simple decreto que ordena el "Traslado" de un escrito hasta la extensa sentencia definitiva que condena al deudor,.;Art. 158 CPC;El legislador las clasifica jerárquicamente en sentencias definitivas, sentencias interlocutorias, autos y decretos o proveídos.|Su correcta naturaleza legal determina la procedencia admisible de los recursos procesales y sus efectos de cosa juzgada.

**Sentencia Definitiva**;Derecho Procesal;Teoría de las Resoluciones;Resolución magna que pone fin a la instancia jurisdiccional, resolviendo y zanjando íntegramente la cuestión o asunto que ha sido objeto principal del pleito.;El fallo del juez de letras que, al terminar todo el proceso civil, condena al ejecutado al pago del crédito insoluto.;Art. 158 CPC;Debe cumplir con formalidades rigurosas que incluyen necesariamente una parte expositiva, considerativa y resolutiva,.|Es la resolución judicial natural y esperada sobre la cual recae con máxima intensidad el efecto inmutable de la cosa juzgada.

**Recurso Procesal**;Derecho Procesal;Medios de Impugnación;Acto jurídico procesal de la parte agraviada, ejercido mediante el cual impugna formalmente una resolución judicial no ejecutoriada, solicitando su revisión para anularla, modificarla o revocarla,.;El litigante perdidoso apela el fallo condenatorio de primera instancia para que la Corte de Apelaciones respectiva lo revise en el fondo,.;Doctrina Procesal (Mosquera / Maturana);Exige de forma ineludible la existencia de un agravio o perjuicio directo causado al interviniente por la decisión del tribunal,.|Constituyen el pilar fundamental que da vida y materializa la garantía procedimental de la doble instancia judicial."""

lines = [l.strip() for l in raw_data.strip().split('\n') if l.strip()]
formatted_lines = []
for line in lines:
    parts = line.split(';')
    # Parts: 0: Concept (with **), 1: Category, 2: Subcategory, 3: Definition, 4: Example, 5: Regulation, 6: KeyPoints
    concept = parts[0].replace('**', '').strip()
    subcategory = parts[2].strip()
    definition = parts[3].strip()
    example = parts[4].strip()
    regulation = parts[5].strip()
    jurisprudence = "" # We'll put an empty string here for compatibility
    key_points = parts[6].strip()
    
    # Format: Concept;Subcategory;Definition;Example;Regulation;Jurisprudence;KeyPoints
    formatted = f"{concept};{subcategory};{definition};{example};{regulation};{jurisprudence};{key_points}"
    formatted_lines.append(formatted)

with open('c:/Users/carlo/OneDrive/Escritorio/iuris/scratch/formatted_new_terms.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(formatted_lines))

print(f"Formatted {len(formatted_lines)} lines.")
