import json
import re

user_data = """Proceso;Derecho Procesal;Teoría General;Medio idóneo para dirimir imparcialmente, por acto de juicio de autoridad, un conflicto de relevancia jurídica mediante una resolución que eventualmente puede adquirir la fuerza de la cosa juzgada.;La tramitación completa de un conflicto por cobro de pesos desde su inicio formal hasta la dictación de la sentencia de término.;Doctrina Procesal;Es un concepto abstracto y único, a diferencia de los múltiples procedimientos o ritualidades existentes.|Su naturaleza es netamente funcional y teleológica, buscando avanzar en el tiempo hacia la resolución del conflicto.

Procedimiento;Derecho Procesal;Teoría General;Conjunto de formalidades, trámites, ritos externos o actuaciones a través de las cuales se desarrolla materialmente el proceso judicial.;El juicio ordinario que establece trámites escritos consecutivos como la demanda, contestación, réplica y dúplica para avanzar el proceso.;Doctrina Procesal;Representa la forma racional y metódica en que deben actuar los tribunales para administrar justicia ordinariamente.|Es el aspecto exterior y dinámico del fenómeno procesal, señalando el orden en que se suceden los actos.

Juicio;Derecho Procesal;Teoría General;Controversia o contienda jurídica y actual que se produce entre dos o más personas sobre un derecho, la cual se somete a la decisión jurisdiccional de un tribunal.;Un litigio entre un arrendador y un arrendatario por el no pago de rentas que requiere un fallo emanado de un juez civil.;Doctrina Procesal;Sus elementos constitutivos esenciales e indispensables son la contienda, las partes litigantes y el tribunal llamado a resolverla.|Suele ser el procedimiento específico a través del cual se materializa en la práctica el proceso (ej. juicio sumario o ejecutivo).

Jurisdicción;Derecho Procesal;Orgánico;Poder-deber que tienen los tribunales para conocer y resolver, por medio del proceso y con efecto de cosa juzgada, los conflictos de intereses de relevancia jurídica temporal.;La Corte Suprema resolviendo un recurso extraordinario de revisión o casación en el fondo con autoridad soberana plena.;Constitución Política y COT;Es indelegable, improrrogable y su carencia genera una inexistencia procesal absoluta de lo resuelto.|Comprende el ejercicio inexcusable de tres momentos esenciales: conocer, juzgar y hacer ejecutar lo juzgado.

Competencia;Derecho Procesal;Orgánico;Esfera, grado o medida específica fijada por el legislador para que la jurisdicción general se ejerza válidamente por cada tribunal.;Un juez de letras de Santiago conoce de un juicio civil porque la ley nacional le asigna competencia por territorio y cuantía material.;COT Art. 108;A diferencia de la jurisdicción, puede delegarse excepcionalmente mediante exhortos y es prorrogable por las partes en ciertos casos.|Puede clasificarse doctrinariamente en absoluta o relativa según factores como la cuantía, la materia, el fuero o el territorio.

Prórroga de la Competencia;Derecho Procesal;Orgánico;Acuerdo expreso o tácito de las partes para otorgar competencia territorial a un tribunal que naturalmente no la tiene para conocer de ese asunto.;El demandado contesta íntegramente la demanda civil ante un tribunal de otra ciudad sin oponer la excepción de incompetencia.;Doctrina Procesal;Sólo opera legalmente en asuntos civiles contenciosos, en primera instancia y únicamente entre tribunales ordinarios respecto del factor territorio.|Puede ser expresa (acuerdo o pacto formal) o tácita (realizar gestiones directas sin reclamar la incompetencia).

Regla de Radicación;Derecho Procesal;Orgánico;Principio normativo que dispone que, radicado con arreglo a la ley el conocimiento de un negocio ante tribunal competente, no se alterará esta competencia por causa sobreviniente.;Un demandado civil cambia de domicilio legal a otra ciudad en medio del juicio, pero el tribunal original sigue siendo plenamente competente para fallar.;COT Art. 109;Requiere la intervención formal de un tribunal competente y una actuación ajustada conforme a derecho procedimental.|En materia civil patrimonial, se produce válidamente y genera el estado de litis pendencia desde la notificación legal de la demanda.

Equivalentes Jurisdiccionales;Derecho Procesal;Teoría General;Formas de solución de conflictos distintas del proceso jurisdiccional que producen un efecto vinculante asimilable a la cosa juzgada.;Las partes logran un avenimiento extrajudicial autorizado o una transacción, poniendo fin al conflicto con la misma fuerza que un fallo judicial.;Doctrina Procesal (Carnelutti);Incluyen primordialmente a la transacción, el avenimiento aprobado por el tribunal y la conciliación.|Permiten aniquilar o extinguir el procedimiento anormalmente sin requerir llegar a una sentencia definitiva dictada por el juez.

Partes;Derecho Procesal;Disposiciones Comunes;Aquellas personas que sostienen formalmente ante un tribunal una contienda jurídica y actual acerca de sus propios derechos e intereses.;El demandante civil que exige el pago de una deuda pecuniaria y el demandado que se niega judicialmente a pagarla.;Doctrina Procesal;Se clasifican fundamentalmente en directas o principales (actor y demandado) e indirectas o accesorias (terceros).|Para actuar válidamente en el juicio exigen gozar de capacidad procesal y representación legal en el caso de ser incapaces.

Terceros;Derecho Procesal;Disposiciones Comunes;Personas distintas del demandante y del demandado que comparecen al juicio por tener comprometido en él un derecho, sosteniendo peticiones armónicas, contradictorias o independientes.;Un legatario que interviene voluntariamente en un juicio principal ordinario donde los herederos discuten la nulidad de un testamento.;Doctrina Procesal;Su intervención procedimental se conoce formalmente en el derecho procesal con el nombre técnico de "Tercería".|Se subclasifican normativamente en terceros coadyuvantes, excluyentes o independientes, según la compatibilidad de sus intereses.

Patrocinio;Derecho Procesal;Comparecencia en Juicio;Contrato por el cual las partes o interesados en un asunto judicial encomiendan a un abogado habilitado la defensa letrada de sus pretensiones ante los tribunales.;Un abogado asume la dirección técnica del caso firmando la primera presentación de la demanda civil como patrocinante.;Ley N° 18.120;El abogado patrocinante responde civil, criminal y disciplinariamente por la conducción y defensa técnica del juicio.|Se diferencia del mandato judicial, ya que el patrocinio se centra en la estrategia de fondo y la defensa jurídica, no en la sola representación representativa.

Mandato Judicial;Derecho Procesal;Comparecencia en Juicio;Contrato procesal mediante el cual una persona otorga a otra facultades suficientes para que la represente formal y válidamente ante los tribunales de justicia.;Un litigante confiere poder notarial por escritura pública a un procurador del número para que actúe en su exclusivo nombre en el litigio civil.;Doctrina Procesal / Ley 18.120;Si no se constituye con apego a los requisitos, el tribunal no proveerá el escrito y tras un plazo fatal lo tendrá por no presentado.|Exige recaer sobre personas cualificadas como abogados habilitados, procuradores del número o postulantes de asistencia judicial.

Demanda;Derecho Procesal;Juicio Ordinario;Acto procesal formal y escrito introductivo de instancia por virtud del cual el actor somete su pretensión al juez, solicitando la protección, declaración o constitución de un derecho.;Un escrito formalizado por el acreedor solicitando al tribunal competente la condena del deudor moroso al pago de un crédito mercantil.;CPC Art. 254;Es la vía formal e inicial mediante la cual se ejercita y materializa la acción procesal y la pretensión del sujeto activo.|Fija irrevocablemente la extensión del juicio y limita en forma estricta los poderes de condena del juez en el fallo definitivo (congruencia procesal).

Emplazamiento;Derecho Procesal;Disposiciones Comunes;Notificación legal de la demanda, indisolublemente unida a la orden del tribunal para que el demandado comparezca a defenderse dentro de un término temporal señalado.;Un receptor judicial notifica la demanda en el domicilio del demandado, concediéndole el plazo fatal de 15 días para contestarla formalmente.;Doctrina Procesal;Constituye un trámite sustancial, cuya omisión grave o notificación viciosa anula todo el procedimiento principal por indefensión.|Se compone jurídicamente de dos elementos copulativos: la notificación válida y el transcurso íntegro del plazo fatal asignado por ley.

Notificación Personal;Derecho Procesal;Notificaciones;Aquella forma legal que consiste en entregar directamente a la persona a quien se debe notificar, en forma física, copia íntegra de la resolución y de la solicitud en que haya recaído.;El ministro de fe le entrega en sus propias manos al demandado principal la primera resolución que admite a tramitación la demanda.;CPC Art. 40;Debe utilizarse obligatoriamente como regla ineludible para la primera notificación a las partes en toda gestión jurisdiccional que les afecte.|Puede practicarse de manera válida en lugares como el oficio del secretario o en la morada temporal o lugar de trabajo del notificado.

Notificación por el Estado Diario;Derecho Procesal;Notificaciones;Ficción legal en que se entiende válidamente notificada una resolución jurisdiccional por el solo hecho de incluirse la causa en una lista electrónica o rol diario en el tribunal.;La resolución judicial que confiere el trámite de traslado para replicar se anota en el estado electrónico y queda comunicada a las partes.;CPC Art. 50;Constituye con creces la regla generalísima para notificar actos procesales de mero trámite a lo largo de todo el proceso civil ordinario.|La lista debe contener la fecha, individualización del tribunal, apellidos de los primeros litigantes y el rol exacto expresado en cifras y letras.

Plazo Fatal;Derecho Procesal;Plazos;Aquel espacio de tiempo perentorio en que la posibilidad de ejercer un derecho procesal o ejecutar un acto se extingue automáticamente a su vencimiento, por el solo ministerio de la ley.;El litigante demandado tiene 15 días hábiles para contestar, transcurridos los cuales pierde irremediablemente su derecho para ese trámite.;CPC Art. 64;La gran generalidad de los plazos que establece el Código de Procedimiento Civil son esencialmente fatales o preclusivos.|No requieren una declaración judicial o rebeldía previa para extinguir procesalmente la facultad temporal no ejercida.

Rebeldía;Derecho Procesal;Plazos;Situación fáctica y jurídica que se le produce al litigante que omite evacuar un trámite o practicar una diligencia en el plazo (no fatal) señalado por el tribunal.;El actor no presenta sus observaciones a la prueba, por lo que el tribunal debe declarar evacuado el trámite en su rebeldía y avanzar.;Doctrina Procesal;Permite acusar la inactividad culpable para que el tribunal provea lo conveniente para la prosecución y no estancamiento del juicio.|El declarado rebelde puede solicitar excepcionalmente la rescisión de lo obrado amparándose en fuerza mayor si la prueba dentro de tres días.

Excepciones Dilatorias;Derecho Procesal;Juicio Ordinario;Defensas procesales formales que el demandado opone para paralizar transitoriamente la demanda, buscando corregir vicios del procedimiento, sin afectar el fondo de la acción deducida.;El demandado opone la incompetencia absoluta del tribunal o la ineptitud del libelo porque la demanda omite detallar el domicilio.;CPC Art. 303;Se tramitan como un incidente procedimental de previo y especial pronunciamiento antes de requerirse la contestación del fondo.|Son taxativas normativamente, pero abiertas por un numeral supletorio que ampara genéricamente correcciones formales del juicio.

Excepciones Perentorias;Derecho Procesal;Juicio Ordinario;Defensas jurídicas de carácter sustancial que miran directamente al fondo del asunto y tienen por exclusivo objeto enervar, destruir o extinguir la acción del actor.;Frente al cobro coactivo, el demandado contesta la demanda alegando y probando el pago íntegro previo o la prescripción extintiva obligacional.;Doctrina Procesal;A diferencia de las defensas dilatorias, no buscan sanear errores del juicio, sino que persiguen que el juez deseche totalmente la demanda en la sentencia final.|Suelen confundirse e identificarse doctrinariamente con los modos civiles de extinguir obligaciones y no se encuentran taxativamente listadas.

Reconvención;Derecho Procesal;Juicio Ordinario;Demanda procesal nueva que el demandado deduce derechamente en contra del demandante en el propio escrito de contestación, aprovechando el procedimiento general ya iniciado.;En un juicio ordinario por incumplimiento, el arrendatario contesta y a su vez demanda (reconviene) exigiendo compensación por mejoras no pagadas.;CPC Art. 314;Se tramita obligatoriamente en paralelo por vía incidental y se falla de manera conjunta en la única sentencia definitiva de la acción matriz.|Busca concretar estrictamente la economía procesal al evitar multiplicar juicios y previniendo el riesgo de dictar sentencias contradictorias.

Incidentes;Derecho Procesal;Disposiciones Comunes;Toda cuestión procedimental accesoria al juicio principal que amerita o requiere de un pronunciamiento judicial especial, procediendo con o sin audiencia previa de las partes.;La impugnación formal de un documento considerado falso introducido como prueba, o la paralizante solicitud de nulidad procesal.;CPC Art. 82;Se subclasifican procesalmente en incidentes ordinarios, especiales, y en incidentes de previo y especial pronunciamiento que suspenden el fondo.|Su tramitación comprende una etapa de discusión con un eventual traslado por tres días y puede requerir un término probatorio de ocho días si existen hechos fácticos controvertidos.

Acumulación de Autos;Derecho Procesal;Incidentes Especiales;Incidente procesal especial que tiene por finalidad obtener que el tribunal ordene agrupar físicamente dos o más procesos pendientes y conexos para tramitarlos y fallarlos conjuntamente.;Se acumula un juicio declarativo de nulidad a otro iniciado sobre cobro del mismo objeto para dictar un fallo único congruente.;CPC Art. 92;Garantiza mantener la llamada continencia de la causa, impidiendo fundamentalmente el riesgo de que distintos tribunales fallen con sentencias contradictorias.|Para su procedencia legal, los juicios afectados deben estar sometidos al mismo tipo de procedimiento y hallarse en instancias análogas de tramitación.

Abandono del Procedimiento;Derecho Procesal;Incidentes Especiales;Incidente especial que, interpuesto a título de sanción, declara la preclusión del procedimiento ante la inactividad de las partes durante seis meses, sin realizar gestión útil.;El demandado opone y pide el abandono porque el demandante dejó el juicio inactivo ocho meses sin solicitar abrir la causa a prueba.;CPC Art. 152;Su declaración extingue el proceso y anula todo lo obrado, pero no extingue directamente la acción material ni el derecho reclamado de fondo.|Sólo puede ser impetrado por el demandado como vía defensiva y su paralización fáctica debe afectar a todas las partes en el proceso.

Desistimiento de la Demanda;Derecho Procesal;Incidentes Especiales;Acto jurídico procesal unilateral, formalizado por el actor en cualquier momento tras la notificación inicial, mediante el cual renuncia explícitamente a su pretensión principal, extinguiendo el proceso.;El demandante, convencido de perder, desiste de su acción reivindicatoria principal perdiendo la oportunidad de deducirla otra vez ante tribunales.;CPC Art. 148;A diferencia del simple retiro, se tramita de manera incidental, requiriendo un pronunciamiento jurisdiccional o interlocutoria que lo ampare.|Produce una fuerte extinción fáctica del procedimiento y genera cosa juzgada respecto de los derechos renunciados.

Medidas Prejudiciales;Derecho Procesal;Medidas Cautelares;Providencias de naturaleza conservadora o preparatoria que puede decretar un tribunal, antes del inicio formal de un juicio, para hacer posible o preparar las futuras acciones o defensas.;Un futuro demandante que pide la exhibición forzada de registros contables privados para construir adecuadamente su próxima demanda civil.;CPC Art. 273;Su uso es típicamente facultativo y su principal justificación es preparar la tutela efectiva para evitar sentencias ilusorias.|La doctrina las subclasifica orgánicamente en prejudiciales preparatorias, probatorias o en prejudiciales netamente precautorias.

Medidas Precautorias;Derecho Procesal;Medidas Cautelares;Providencias dictadas jurisdiccionalmente durante el curso de un juicio, dirigidas a asegurar el resultado práctico de la acción civil, que requieren acreditar presunción grave y peligro en la demora.;La retención judicial de bienes muebles, dineros bancarios o la prohibición de celebrar contratos sobre un bien raíz en disputa.;CPC Art. 290;Aseguran el objetivo práctico del litigio previniendo que la futura sentencia termine volviéndose ilusoria por insolvencia fraudulenta.|Son esencialmente provisionales (modificables), deben ser racionales limitándose a lo adeudado y son sustituibles por otras cauciones solventes.

Resoluciones Judiciales;Derecho Procesal;Resoluciones;Acto jurídico procesal reglado y emitido formalmente por el tribunal o sus auxiliares, que posee por objeto dar curso progresivo a la sustanciación o sentenciar la litis sometida a fallo.;El laudo que condena al demandado al resarcimiento o la simple providencia menor dictada como "Traslado" ante un escrito presentado.;CPC Art. 158;La ley las clasifica jerárquicamente como sentencias definitivas, sentencias interlocutorias de varios grados, los autos menores y los decretos formales.|La tipología particular de la resolución define procesalmente la vía admisible para impugnación (recursos) y el alcance de su efecto firme.

Sentencia Definitiva;Derecho Procesal;Resoluciones;Resolución magna que tiene por fin exclusivo poner término material a la instancia, resolviendo y zanjando íntegramente la cuestión o asunto matriz que ha sido objeto del pleito.;El fallo del juez civil que luego de meses de tramitación acoge la demanda sobre indemnización extracontractual y condena pecuniariamente al infractor.;CPC Art. 158;Debe contener en su diseño imperativo una parte expositiva, una considerativa de justificación y, vitalmente, la parte resolutiva y dispositiva.|Es la única resolución que adquiere estricta autoridad irremediable de cosa juzgada material al transcurrir o agotarse los recursos interpuestos.

Recurso Procesal;Derecho Procesal;Recursos;Acto jurídico procesal formal ejercido por la parte agraviada dentro del proceso para impugnar una resolución judicial que aún no está ejecutoriada, buscando anularla, modificarla o revocarla en otra sede.;El litigante perdidoso apela el fallo condenatorio ante el tribunal inferior para que la Corte lo revise en el fondo y dicte su absolución en segunda instancia.;Doctrina Procesal;Todo recurso exige para operar la legitimación pasiva de haber recibido un agravio (perjuicio comprobado) derivado de una resolución de tribunal.|Opera bajo un principio estricto de legalidad de los recursos, implicando que no puede interponerse o crearse una impugnación que no fije expresamente la ley."""

lines = [l.strip() for l in user_data.split('\n') if l.strip()]
sql_stmt = "INSERT INTO legal_concepts (id, concept, category, subcategory, definition_simple, real_example, regulation, jurisprudence, video_url, key_points) VALUES\n"
values = []

# Starting from DP-032 because max was DP-031
start_id = 32

for i, line in enumerate(lines):
    parts = line.split(';')
    if len(parts) < 7:
        print(f"Skipping line {i}: {line}")
        continue
        
    concept = parts[0].strip()
    category = parts[1].strip()
    subcategory = parts[2].strip()
    definition = parts[3].strip()
    example = parts[4].strip()
    regulation = parts[5].strip()
    kp_raw = parts[6].strip()
    key_points = [p.strip() for p in kp_raw.split('|') if p.strip()]
    
    concept_id = f"DP-{start_id + i:03d}"
    
    def esc(s):
        return s.replace("'", "''")

    val_str = f"('{concept_id}', '{esc(concept)}', '{esc(category)}', '{esc(subcategory)}', '{esc(definition)}', '{esc(example)}', '{esc(regulation)}', '', '', '{json.dumps(key_points, ensure_ascii=False)}')"
    values.append(val_str)

sql_stmt += ",\n".join(values) + ";"

with open('c:/Users/carlo/OneDrive/Escritorio/iuris/scratch/new_terms.sql', 'w', encoding='utf-8') as f:
    f.write(sql_stmt)

print("SQL generated in c:/Users/carlo/OneDrive/Escritorio/iuris/scratch/new_terms.sql")
